version: "3.6"

services:
    postgres:
        container_name: postgres-bot
        image: postgres:13
        restart: always
        env_file:
            - .env
        environment:
            - POSTGRES_PASSWORD=${PG_PASSWORD}
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_DB=${PG_NAME}
            - PGDATA=${PG_DATA}
        ports:
            - ${PG_PORT}:${PG_PORT}
        expose:
            - ${PG_PORT}
        volumes:
            - /usr/src/app/data:/var/lib/postgresql/data/pgdata
    bot:
        build:
            context: get_truck_number
            dockerfile: Dockerfile
        container_name: "telegram-bot"
        restart: always
        env_file:
            - .env




